"""A from-scratch NumPy CNN, following the course student guide.

All image data is NHWC: ``(batch_size, height, width, channels)``.

Layers implement ``__call__`` (forward), ``backward`` (returns the gradient
w.r.t. their input) and, when they hold parameters, ``update``.
``CNNClassifier`` chains feature layers with a flatten step, a
``ModularLinearLayer`` and a ``SoftmaxLayer``, trained with mini-batch
gradient descent on the cross-entropy loss.
"""

from __future__ import annotations

from typing import List, Optional, Sequence, Tuple, Union

import numpy as np

__all__ = [
    "get_patches",
    "pad_images",
    "ConvLayer",
    "PoolingLayer",
    "ReLULayer",
    "SoftmaxLayer",
    "ModularLinearLayer",
    "CNNClassifier",
]

SizeLike = Union[int, Tuple[int, int]]


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

# Generated By LLM _as_pair, get_patches, pad_images, _dilate
def _as_pair(value: SizeLike, name: str) -> Tuple[int, int]:
    """Normalize an int or (h, w) sequence to a tuple of two positive ints."""
    if isinstance(value, (int, np.integer)):
        pair = (int(value), int(value))
    else:
        pair = (int(value[0]), int(value[1]))
    if pair[0] <= 0 or pair[1] <= 0:
        raise ValueError(f"{name} must be positive, got {value}")
    return pair


def get_patches(
    arr: np.ndarray,
    patch_shape: Tuple[int, int],
    strides: Tuple[int, int] = (1, 1),
) -> np.ndarray:
    """Extract sliding-window patches from a batch of images.

    Parameters
    ----------
    arr : ndarray of shape (batch_size, height, width, channels)
    patch_shape : (patch_h, patch_w)
    strides : (stride_h, stride_w)

    Returns
    -------
    ndarray of shape (batch_size, out_h, out_w, channels, patch_h, patch_w)
        A read-only view (no copy) of every patch position.
    """
    if arr.ndim != 4:
        raise ValueError(f"expected a 4D (B, H, W, C) array, got shape {arr.shape}")
    patches = np.lib.stride_tricks.sliding_window_view(arr, patch_shape, axis=(1, 2))
    return patches[:, :: strides[0], :: strides[1]]


def pad_images(X: np.ndarray, padding) -> np.ndarray:
    """Zero-pad the spatial dimensions of a batch of images.

    Parameters
    ----------
    X : ndarray of shape (batch_size, height, width, channels)
    padding : int, or ((top, bottom), (left, right))
        Pixels to add on each spatial side.

    Returns
    -------
    Padded ndarray of shape (batch_size, height + pads, width + pads, channels)
    """
    if isinstance(padding, (int, np.integer)):
        pad_h = pad_w = (int(padding), int(padding))
    else:
        pad_h, pad_w = tuple(padding[0]), tuple(padding[1])
    if pad_h == (0, 0) and pad_w == (0, 0):
        return X
    return np.pad(X, ((0, 0), pad_h, pad_w, (0, 0)))


def _dilate(grad: np.ndarray, stride: Tuple[int, int]) -> np.ndarray:
    """Insert stride-1 zeros between spatial positions of a gradient map.

    Turns the gradient of a strided convolution into an equivalent stride-1
    gradient so the standard backprop formulas apply.
    """
    if stride == (1, 1):
        return grad
    b, h, w, c = grad.shape
    dilated = np.zeros(
        (b, (h - 1) * stride[0] + 1, (w - 1) * stride[1] + 1, c), dtype=grad.dtype
    )
    dilated[:, :: stride[0], :: stride[1]] = grad
    return dilated


# ---------------------------------------------------------------------------
# ConvLayer
# ---------------------------------------------------------------------------

class ConvLayer:
    """2D convolutional layer: slides learnable filters over the image to extract features."""

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: SizeLike,
        stride: SizeLike = 1,
        padding: Union[int, str] = 0,
        rng: Optional[np.random.RandomState] = None,
    ):
        """Create the layer: Xavier-uniform weights, zero biases."""
        self.in_channels = int(in_channels)
        self.out_channels = int(out_channels)
        self.kernel_size = _as_pair(kernel_size, "kernel_size")
        self.stride = _as_pair(stride, "stride")
        self.padding = padding

        rng = rng if rng is not None else np.random.RandomState()
        kH, kW = self.kernel_size
        fan_in = self.in_channels * kH * kW
        fan_out = self.out_channels * kH * kW
        limit = np.sqrt(6.0 / (fan_in + fan_out))
        # kernel weights of shape (out_channels, in_channels, kH, kW)
        self.weight = rng.uniform(
            -limit, limit, (self.out_channels, self.in_channels, kH, kW)
        )
        self.bias = np.zeros(self.out_channels)
        # aliases used by the course evaluator
        self.weight_ = self.weight
        self.bias_ = self.bias

        self._weight_grad: Optional[np.ndarray] = None
        self._bias_grad: Optional[np.ndarray] = None
        self._prev_input: Optional[np.ndarray] = None
        self._weight_velocity: Optional[np.ndarray] = None
        self._bias_velocity: Optional[np.ndarray] = None

    def _pad_amounts(self) -> Tuple[Tuple[int, int], Tuple[int, int]]:
        """Resolve the padding setting to ((top, bottom), (left, right))."""
        kH, kW = self.kernel_size
        if isinstance(self.padding, str):
            mode = self.padding.lower()
            if mode == "valid":
                return (0, 0), (0, 0)
            if mode == "same":
                return (
                    ((kH - 1) // 2, kH - 1 - (kH - 1) // 2),
                    ((kW - 1) // 2, kW - 1 - (kW - 1) // 2),
                )
            raise ValueError(f"unknown padding mode {self.padding!r}")
        p = int(self.padding)
        return (p, p), (p, p)

    def _pad(self, X: np.ndarray, padding=None) -> np.ndarray:
        """Apply this layer's padding (or an explicit override) to X."""
        if padding is None:
            padding = self._pad_amounts()
        return pad_images(X, padding)

    def __call__(self, X: np.ndarray) -> np.ndarray:
        """Forward pass: convolution + bias.

        Args:
            X: ndarray of shape (batch_size, height, width, in_channels)

        Returns:
            ndarray of shape (batch_size, out_height, out_width, out_channels)
        """
        if X.ndim != 4:
            raise ValueError(f"expected (B, H, W, C) input, got shape {X.shape}")
        if X.shape[-1] != self.in_channels:
            raise ValueError(
                f"expected {self.in_channels} input channels, got {X.shape[-1]}"
            )
        self._prev_input = X
        Xp = self._pad(X)
        patches = get_patches(Xp, self.kernel_size, self.stride)
        return np.einsum("bxyihw,oihw->bxyo", patches, self.weight) + self.bias

    def backward(
        self, grad_output: np.ndarray, alpha: Optional[float] = None
    ) -> np.ndarray:
        """Compute gradients w.r.t. input, weights, and biases.

        ``alpha`` adds an L2 penalty gradient (``alpha * weight``) to the
        weight gradient.
        """
        if self._prev_input is None:
            raise RuntimeError("run the forward pass before calling backward()")
        kH, kW = self.kernel_size
        Xp = self._pad(self._prev_input)
        Hp, Wp = Xp.shape[1], Xp.shape[2]

        # a strided convolution's gradient equals a stride-1 gradient with
        # zeros between the positions the kernel actually visited
        grad = _dilate(grad_output, self.stride)
        Hd, Wd = grad.shape[1], grad.shape[2]

        # dJ/dW = input (x) delta
        input_patches = get_patches(Xp, self.kernel_size)[:, :Hd, :Wd]
        self._weight_grad = np.einsum("bxyihw,bxyo->oihw", input_patches, grad)
        if alpha:
            self._weight_grad = self._weight_grad + alpha * self.weight
        self._bias_grad = np.sum(grad_output, axis=(0, 1, 2))

        # dJ/dX = full convolution of delta with the 180°-rotated kernel
        grad_full = pad_images(grad, ((kH - 1, kH - 1), (kW - 1, kW - 1)))
        grad_patches = get_patches(grad_full, self.kernel_size)
        flipped = np.flip(self.weight, axis=(-2, -1))
        grad_input = np.einsum("bxyohw,oihw->bxyi", grad_patches, flipped)

        # positions the kernel never reached (input size not divisible by the
        # stride) receive zero gradient
        residual_h = Hp - grad_input.shape[1]
        residual_w = Wp - grad_input.shape[2]
        if residual_h or residual_w:
            grad_input = pad_images(grad_input, ((0, residual_h), (0, residual_w)))

        # crop off the forward padding
        (top, bottom), (left, right) = self._pad_amounts()
        grad_input = grad_input[:, top : Hp - bottom, left : Wp - right, :]
        return grad_input

    def update(self, learning_rate: float, momentum: float = 0.0) -> None:
        """Update weights and biases (gradient descent, optionally with momentum)."""
        if self._weight_grad is None:
            raise RuntimeError("call backward() before update()")
        if momentum:
            if self._weight_velocity is None:
                self._weight_velocity = np.zeros_like(self.weight)
                self._bias_velocity = np.zeros_like(self.bias)
            self._weight_velocity = (
                momentum * self._weight_velocity - learning_rate * self._weight_grad
            )
            self._bias_velocity = (
                momentum * self._bias_velocity - learning_rate * self._bias_grad
            )
            self.weight += self._weight_velocity
            self.bias += self._bias_velocity
        else:
            self.weight -= learning_rate * self._weight_grad
            self.bias -= learning_rate * self._bias_grad

    def get_output_shape(self, input_shape: Tuple[int, int, int]) -> Tuple[int, int, int]:
        """Output (height, width, channels) for an input (height, width, channels)."""
        h, w = input_shape[0], input_shape[1]
        (top, bottom), (left, right) = self._pad_amounts()
        kH, kW = self.kernel_size
        sH, sW = self.stride
        out_h = (h + top + bottom - kH) // sH + 1
        out_w = (w + left + right - kW) // sW + 1
        return (out_h, out_w, self.out_channels)

    def __repr__(self) -> str:
        """Readable description of the layer configuration."""
        return (
            f"ConvLayer({self.in_channels}, {self.out_channels}, "
            f"kernel_size={self.kernel_size}, stride={self.stride}, "
            f"padding={self.padding!r})"
        )


# ---------------------------------------------------------------------------
# PoolingLayer
# ---------------------------------------------------------------------------

class PoolingLayer:
    """Max-pooling layer: shrinks each feature map by keeping the largest value per window."""

    def __init__(self, pool_size: SizeLike = 2, stride: SizeLike = 2, padding: int = 0):
        """Create a max-pooling layer with the given window size and stride."""
        self.pool_size = _as_pair(pool_size, "pool_size")
        self.stride = _as_pair(stride, "stride")
        self.padding = int(padding)
        # alias used by the course evaluator
        self.kernel_size = self.pool_size
        self._prev_input: Optional[np.ndarray] = None
        self._previous_input: Optional[np.ndarray] = None

    def __call__(self, X: np.ndarray) -> np.ndarray:
        """Forward pass: apply max pooling.

        Args:
            X: ndarray of shape (batch_size, height, width, channels)

        Returns:
            ndarray of shape (batch_size, out_height, out_width, channels)
        """
        if X.ndim != 4:
            raise ValueError(f"expected (B, H, W, C) input, got shape {X.shape}")
        X = pad_images(X, self.padding)
        self._prev_input = X
        self._previous_input = X
        patches = get_patches(X, self.pool_size, self.stride)
        return np.max(patches, axis=(-2, -1))

    def backward(self, grad_output: np.ndarray) -> np.ndarray:
        """Route gradients back through max positions."""
        if self._prev_input is None:
            raise RuntimeError("run the forward pass before calling backward()")
        X = self._prev_input
        pH, pW = self.pool_size
        sH, sW = self.stride

        patches = get_patches(X, self.pool_size, self.stride)
        b, out_h, out_w, c = grad_output.shape
        flat = patches.reshape(b, out_h, out_w, c, pH * pW)
        winner = np.argmax(flat, axis=-1)
        win_h, win_w = winner // pW, winner % pW

        bi, oy, ox, ci = np.indices((b, out_h, out_w, c), sparse=False)
        grad_input = np.zeros_like(X)
        # add.at accumulates when windows overlap (stride < pool size)
        np.add.at(
            grad_input,
            (bi, oy * sH + win_h, ox * sW + win_w, ci),
            grad_output,
        )
        if self.padding:
            p = self.padding
            grad_input = grad_input[:, p : grad_input.shape[1] - p, p : grad_input.shape[2] - p, :]
        return grad_input

    def get_output_shape(self, input_shape: Tuple[int, int, int]) -> Tuple[int, int, int]:
        """Output (height, width, channels) for an input (height, width, channels)."""
        h, w = input_shape[0] + 2 * self.padding, input_shape[1] + 2 * self.padding
        out_h = (h - self.pool_size[0]) // self.stride[0] + 1
        out_w = (w - self.pool_size[1]) // self.stride[1] + 1
        return (out_h, out_w, input_shape[2])

    def __repr__(self) -> str:
        """Readable description of the layer configuration."""
        return f"PoolingLayer(pool_size={self.pool_size}, stride={self.stride})"


# ---------------------------------------------------------------------------
# activation layers
# ---------------------------------------------------------------------------

class ReLULayer:
    """ReLU activation layer: f(x) = max(0, x)."""

    def __init__(self):
        """Create the activation layer (no parameters)."""
        self._mask: Optional[np.ndarray] = None
        self._prev_result: Optional[np.ndarray] = None

    def __call__(self, X: np.ndarray) -> np.ndarray:
        """Forward pass: zero out negative values, keep positive ones."""
        self._mask = X > 0
        self._prev_result = np.maximum(0.0, X)
        return self._prev_result

    def backward(self, grad_output: np.ndarray) -> np.ndarray:
        """Backward pass: let gradients through only where the input was positive."""
        if self._mask is None:
            raise RuntimeError("run the forward pass before calling backward()")
        return grad_output * self._mask

    def __repr__(self) -> str:
        """Readable description of the layer."""
        return "ReLULayer()"


class SoftmaxLayer:
    """Softmax activation layer: maps class scores to probabilities that sum to 1."""

    def __init__(self):
        """Create the activation layer (no parameters)."""
        self._prev_result: Optional[np.ndarray] = None

    def __call__(self, X: np.ndarray) -> np.ndarray:
        """Forward pass: turn each row of scores into a probability distribution."""
        # subtracting the row max keeps exp() from overflowing
        shifted = X - np.max(X, axis=-1, keepdims=True)
        exp = np.exp(shifted)
        self._prev_result = exp / np.sum(exp, axis=-1, keepdims=True)
        return self._prev_result

    def backward(self, grad_output: np.ndarray) -> np.ndarray:
        """Backward pass: gradient through the softmax function."""
        # full Jacobian-vector product: p * (g - sum(g * p))
        if self._prev_result is None:
            raise RuntimeError("run the forward pass before calling backward()")
        p = self._prev_result
        return p * (grad_output - np.sum(grad_output * p, axis=-1, keepdims=True))

    def __repr__(self) -> str:
        """Readable description of the layer."""
        return "SoftmaxLayer()"


# ---------------------------------------------------------------------------
# ModularLinearLayer
# ---------------------------------------------------------------------------

class ModularLinearLayer:
    """Fully connected layer computing ``X @ weight + bias`` for classification heads."""

    def __init__(
        self,
        input_size: int,
        output_size: int,
        rng: Optional[np.random.RandomState] = None,
    ):
        """Create the layer: Xavier-uniform weights, zero biases."""
        self.input_size = int(input_size)
        self.output_size = int(output_size)
        # aliases used by the course evaluator
        self.in_features = self.input_size
        self.out_features = self.output_size

        rng = rng if rng is not None else np.random.RandomState()
        limit = np.sqrt(6.0 / (self.input_size + self.output_size))
        self.weight = rng.uniform(-limit, limit, (self.input_size, self.output_size))
        self.bias = np.zeros(self.output_size)
        self.weight_ = self.weight
        self.bias_ = self.bias

        self._weight_grad: Optional[np.ndarray] = None
        self._bias_grad: Optional[np.ndarray] = None
        self._prev_input: Optional[np.ndarray] = None
        self._weight_velocity: Optional[np.ndarray] = None
        self._bias_velocity: Optional[np.ndarray] = None

    def __call__(self, X: np.ndarray) -> np.ndarray:
        """Forward pass: X @ weight + bias."""
        if X.ndim != 2 or X.shape[1] != self.input_size:
            raise ValueError(
                f"expected input of shape (batch, {self.input_size}), got {X.shape}"
            )
        self._prev_input = X
        return X.dot(self.weight) + self.bias

    def backward(
        self, grad_output: np.ndarray, alpha: Optional[float] = None
    ) -> np.ndarray:
        """Compute gradients w.r.t. input, weights, and biases.

        ``alpha`` adds an L2 penalty gradient (``alpha * weight``) to the
        weight gradient.
        """
        if self._prev_input is None:
            raise RuntimeError("run the forward pass before calling backward()")
        self._weight_grad = self._prev_input.T.dot(grad_output)
        if alpha:
            self._weight_grad = self._weight_grad + alpha * self.weight
        self._bias_grad = np.sum(grad_output, axis=0)
        return grad_output.dot(self.weight.T)

    def update(self, learning_rate: float, momentum: float = 0.0) -> None:
        """Update weights and biases (gradient descent, optionally with momentum)."""
        if self._weight_grad is None:
            raise RuntimeError("call backward() before update()")
        if momentum:
            if self._weight_velocity is None:
                self._weight_velocity = np.zeros_like(self.weight)
                self._bias_velocity = np.zeros_like(self.bias)
            self._weight_velocity = (
                momentum * self._weight_velocity - learning_rate * self._weight_grad
            )
            self._bias_velocity = (
                momentum * self._bias_velocity - learning_rate * self._bias_grad
            )
            self.weight += self._weight_velocity
            self.bias += self._bias_velocity
        else:
            self.weight -= learning_rate * self._weight_grad
            self.bias -= learning_rate * self._bias_grad

    def __repr__(self) -> str:
        """Readable description of the layer configuration."""
        return f"ModularLinearLayer({self.input_size}, {self.output_size})"


# ---------------------------------------------------------------------------
# CNNClassifier
# ---------------------------------------------------------------------------

class CNNClassifier:
    """Convolutional Neural Network for image classification.

    Chains the feature layers, flattens their output, and adds a linear +
    softmax head. Trained with mini-batch SGD (momentum, optional learning-rate
    decay and early stopping) on the cross-entropy loss.
    """

    def __init__(
        self,
        input_shape: Tuple[int, int, int] = (28, 28, 1),
        num_classes: int = 10,
        lr: float = 0.01,
        epochs: int = 20,
        batch_size: int = 32,
        random_state: Optional[int] = None,
        layers: Optional[Sequence] = None,
        alpha: float = 0.0,
        verbose: bool = True,
        momentum: float = 0.9,
        lr_decay: float = 0.0,
        early_stopping: bool = True,
        tol: float = 1e-4,
        n_iter_no_change: int = 5,
        max_grad_norm: Optional[float] = None,
    ):
        # Generated By LLM 
        """Store and validate the hyperparameters (nothing is trained yet)."""
        if lr <= 0:
            raise ValueError(f"lr must be positive, got {lr}")
        if int(epochs) <= 0:
            raise ValueError(f"epochs must be positive, got {epochs}")
        if int(batch_size) <= 0:
            raise ValueError(f"batch_size must be positive, got {batch_size}")
        if alpha < 0:
            raise ValueError(f"alpha must be non-negative, got {alpha}")
        if not 0.0 <= momentum < 1.0:
            raise ValueError(f"momentum must be in [0, 1), got {momentum}")
        if lr_decay < 0:
            raise ValueError(f"lr_decay must be non-negative, got {lr_decay}")

        self.input_shape = tuple(input_shape)
        self.num_classes = int(num_classes)
        self.lr = lr
        self.epochs = int(epochs)
        self.batch_size = int(batch_size)
        self.random_state = random_state
        self.alpha = alpha
        self.verbose = verbose
        self.momentum = momentum
        self.lr_decay = lr_decay
        self.early_stopping = early_stopping
        self.tol = tol
        self.n_iter_no_change = int(n_iter_no_change)
        self.max_grad_norm = max_grad_norm
        # list of layer objects (set during build/fit)
        self.layers_: List = list(layers) if layers is not None else []
        self._given_layers = layers

    # -- architecture ------------------------------------------------------

    def _build_layers(self) -> List:
        """Default feature-extraction stack when no layers were given.

        Pooling halves the spatial size, so it is only added while the
        feature map stays at least 4x4 - small inputs (e.g. 8x8 digits)
        would otherwise be crushed to almost nothing.
        """
        h, w, channels = self.input_shape
        layers: List = [
            ConvLayer(channels, 8, 3, padding="same", rng=self.rng_),
            ReLULayer(),
        ]
        if min(h, w) >= 8:
            layers.append(PoolingLayer(2, 2))
            h, w = h // 2, w // 2
        layers += [
            ConvLayer(8, 16, 3, padding="same", rng=self.rng_),
            ReLULayer(),
        ]
        if min(h, w) >= 8:
            layers.append(PoolingLayer(2, 2))
        return layers

    def _feature_shape(self) -> Tuple[int, int, int]:
        """Shape (h, w, c) coming out of the last feature layer."""
        shape = self.input_shape
        for layer in self.layers_:
            if hasattr(layer, "get_output_shape"):
                shape = layer.get_output_shape(shape)
        if shape[0] <= 0 or shape[1] <= 0:
            raise ValueError(
                f"layer stack reduces {self.input_shape} to empty output {shape}"
            )
        return shape

    # -- forward / loss ----------------------------------------------------

    def _forward(self, X: np.ndarray) -> np.ndarray:
        """Forward pass through all layers; returns class probabilities."""
        res = X
        for layer in self.layers_:
            res = layer(res)
        self._feat_shape_ = res.shape[1:]
        res = res.reshape(len(res), -1)
        res = self.out_layer_(res)
        return self.softmax_layer_(res)

    def _calculate_loss(
        self, logits: np.ndarray, y: np.ndarray
    ) -> Tuple[float, np.ndarray]:
        """Cross-entropy loss (+ L2 penalty) and its gradient w.r.t. the probabilities.

        Args:
            logits: predicted class probabilities, shape (batch, num_classes)
            y: one-hot targets of the same shape
        """
        batch = len(y)
        probs = np.clip(logits, 1e-12, None)
        loss = float(-np.sum(y * np.log(probs)) / batch)
        if self.alpha:
            l2 = sum(
                float(np.sum(layer.weight ** 2))
                for layer in [*self.layers_, self.out_layer_]
                if hasattr(layer, "weight")
            )
            loss += 0.5 * self.alpha * l2
        grad = -(y / probs) / batch
        return loss, grad

    def _backward(self, grad: np.ndarray) -> None:
        """Propagate the loss gradient back through every layer."""
        grad = self.softmax_layer_.backward(grad)
        grad = self.out_layer_.backward(grad, self.alpha)
        grad = grad.reshape(len(grad), *self._feat_shape_)
        for layer in reversed(self.layers_):
            if hasattr(layer, "update"):
                grad = layer.backward(grad, self.alpha)
            else:
                grad = layer.backward(grad)

    # Generated By LLM 
    def _clip_gradients(self) -> None:
        """Scale all parameter gradients so their global L2 norm <= max_grad_norm."""
        if self.max_grad_norm is None:
            return
        param_layers = [l for l in [*self.layers_, self.out_layer_] if hasattr(l, "update")]
        total = np.sqrt(
            sum(
                float(np.sum(l._weight_grad ** 2)) + float(np.sum(l._bias_grad ** 2))
                for l in param_layers
            )
        )
        if total > self.max_grad_norm:
            scale = self.max_grad_norm / (total + 1e-12)
            for l in param_layers:
                l._weight_grad = l._weight_grad * scale
                l._bias_grad = l._bias_grad * scale

    def _update(self, learning_rate: float) -> None:
        """Apply one gradient-descent step to every layer with parameters."""
        for layer in self.layers_:
            if hasattr(layer, "update"):
                layer.update(learning_rate, self.momentum)
        self.out_layer_.update(learning_rate, self.momentum)

    def _validate_images(self, X) -> np.ndarray:
        """Cast to a float64 NHWC batch, tolerating a missing single-channel dim."""
        X = np.asarray(X, dtype=float)
        if X.ndim == 3 and self.input_shape[2] == 1:
            X = X[..., None]
        if X.ndim != 4:
            raise ValueError(f"expected (n, H, W, C) input, got shape {X.shape}")
        return X

    # -- public API --------------------------------------------------------

    def fit(self, X: np.ndarray, y: np.ndarray) -> "CNNClassifier":
        """Train the CNN.

        Args:
            X: ndarray of shape (n_samples, height, width, channels)
            y: ndarray of shape (n_samples,) with integer class labels
        """
        X = self._validate_images(X)
        y = np.asarray(y).ravel()
        
        # Generated By LLM 
        if len(X) == 0:
            raise ValueError("cannot fit on an empty dataset")
        if len(y) != len(X):
            raise ValueError(f"X has {len(X)} samples but y has {len(y)} labels")
        if X.shape[1:] != tuple(self.input_shape):
            raise ValueError(
                f"input shape {X.shape[1:]} does not match input_shape={self.input_shape}"
            )
        if not np.isfinite(X).all():
            raise ValueError("X contains NaN or infinite values")
        if not np.issubdtype(y.dtype, np.integer):
            if not np.all(np.mod(y, 1) == 0):
                raise ValueError("y must contain integer class labels")
            y = y.astype(int)
        if (y < 0).any():
            raise ValueError("class labels must be non-negative integers")

        self.rng_ = np.random.RandomState(self.random_state)
        self.layers_ = (
            list(self._given_layers)
            if self._given_layers is not None
            else self._build_layers()
        )
        n_classes = max(self.num_classes, int(y.max()) + 1)
        feat_h, feat_w, feat_c = self._feature_shape()
        self.out_layer_ = ModularLinearLayer(
            feat_h * feat_w * feat_c, n_classes, rng=self.rng_
        )
        self.softmax_layer_ = SoftmaxLayer()

        onehot = np.zeros((len(y), n_classes))
        onehot[np.arange(len(y)), y] = 1.0

        best_loss = np.inf
        stagnant_epochs = 0
        for epoch in range(self.epochs):
            # inverse-time learning-rate decay (constant when lr_decay=0)
            learning_rate = self.lr / (1.0 + self.lr_decay * epoch)
            order = self.rng_.permutation(len(X))
            losses = []
            for start in range(0, len(X), self.batch_size):
                batch = order[start : start + self.batch_size]
                probs = self._forward(X[batch])
                loss, grad = self._calculate_loss(probs, onehot[batch])
                losses.append(loss)
                self._backward(grad)
                self._clip_gradients()
                self._update(learning_rate)
            epoch_loss = float(np.mean(losses))
            if self.verbose:
                print(f"Epoch {epoch} Loss {epoch_loss:.4f}")
            if epoch_loss < best_loss - self.tol:
                best_loss = epoch_loss
                stagnant_epochs = 0
            else:
                stagnant_epochs += 1
                if self.early_stopping and stagnant_epochs >= self.n_iter_no_change:
                    if self.verbose:
                        print(
                            f"Early stopping at epoch {epoch}: loss has not improved "
                            f"by more than {self.tol} for {self.n_iter_no_change} epochs"
                        )
                    break
        return self

    def predict(self, X: np.ndarray) -> np.ndarray:
        """Predict class labels.

        Args:
            X: ndarray of shape (n_samples, height, width, channels)

        Returns:
            ndarray of shape (n_samples,) with predicted class labels
        """
        if not hasattr(self, "out_layer_"):
            raise RuntimeError("this CNNClassifier is not fitted yet; call fit() first")
        X = self._validate_images(X)
        preds = []
        # chunked evaluation keeps the patch views from ballooning memory
        chunk = max(self.batch_size, 64)
        for start in range(0, len(X), chunk):
            probs = self._forward(X[start : start + chunk])
            preds.append(np.argmax(probs, axis=1))
        return np.concatenate(preds)

    def score(self, X: np.ndarray, y: np.ndarray) -> float:
        """Mean accuracy on the given data."""
        return float(np.mean(self.predict(X) == np.asarray(y)))

    def __repr__(self) -> str:
        """Readable description of the classifier configuration."""
        return (
            f"CNNClassifier(input_shape={self.input_shape}, "
            f"num_classes={self.num_classes}, lr={self.lr}, epochs={self.epochs}, "
            f"batch_size={self.batch_size}, alpha={self.alpha})"
        )
